version: '3.9'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pw1
      - SCHEMA=store
      - POSTGRES_DB=store
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
#    To connect to the database, you need to use the following credentials:
#     host.docker.internal
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
#      Use the following credentials to log in:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    # For better performance, consider `host` mode instead `port` to avoid docker NAT.
    # `host` mode is NOT currently supported in Swarm Mode.
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
    # network_mode: "host"
    volumes:
      - dragonflydata:/data
  app:
    image: 'store:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: store
    ports:
      - '8080:8080'

volumes:
  pgadmin:
  dragonflydata:
  db:
    driver: local